### ISSUE TITLE
Panel interface limits

### ISSUE THREAD

**Issue by mayacakmak** [mayacakmak/se2#13]
While most controls do not allow the object to get outside the workspace, the panel control can send the object off limits--we need to implement check so the object doesn't move once it hits the walls of the workspace.

**Comment by kavidey** [comment]
I just added a check to `ee.translateBy` (and `translateX/YBy`) that limits the x and y location to within the bounds of the workspace: [Code](https://github.com/mayacakmak/se2/blob/master/scripts/se2.js#L248)

**Comment by kavidey** [comment]
Right now, the EE can go all the way to the bounds of the workspace:
![image](https://user-images.githubusercontent.com/16945761/90808555-0ea7a280-e2d5-11ea-9bba-898dcdc30fe2.png)
![image](https://user-images.githubusercontent.com/16945761/90808608-267f2680-e2d5-11ea-9784-a007e49eeee1.png)

We might want to add a boundary so that it can't get so close to the edge.
