### ISSUE TITLE
Flexible target visualizations

### ISSUE THREAD

**Issue by mayacakmak** [mayacakmak/se2#6]
Currently the interface has 'exact' targets, where the SE2 object (dot and line specified by an x,y  position and theta rotation) needs to be taken to an exact target pose (even though there is a small threshold around the exact pose). We would like to be able to specify flexible targets, where the goal is to bring the object within some range near a given SE2 pose. We can do this by changing that small threshold but we need the visualization of the target to reflect the thresholds.
* Flexible position: This can simply be a larger circle at the center. We need to ensure: (1) the threshold is applied to Euclidian distance, not x and y separately (L1 distance); (2) the desired rotation is still clear (e.g. dashed line over the larger circle, perhaps extend length of the rotation line by radius of circle).
* Flexible rotation: Use an arc/pizza slice-like visualization to represent flexibility in rotation. Ensure the position (small point) is still distinct.
* Both (optional): Not sure this is feasible or necessary, but perhaps good to have the option.

**Comment by kavidey** [comment]
I put together some possible visualization in photoshop (these were all done by hand but could easily be done on the website)

![image](https://user-images.githubusercontent.com/16945761/87989831-9a8c9b80-ca97-11ea-8b08-a162f1895d53.png)

`a` and `b` are different ways to show flexible rotation
`d` and `e` are different ways to show flexible position
`c` and `f` are ways that we might show both flexible position and rotation

**Comment by mayacakmak** [comment]
Between the dashed line indicators and faded crag indicators, I prefer the faded gray ones for better visibility (they're also likely to be easier to implement).

For the systematic study we should probably allow situations similar to (f).

One idea that came up in our meeting is to visualize the thresh_xy and thresh_theta variables with slightly different colors (perhaps shades of gray or two shades of a different color). Keep the thresh_xy circle at the front. Keep the size of the thresh_theta pizza slice slightly longer than max_xy so it is still visible even when thresh_xy is largest.

**Comment by kavidey** [comment]
I have implemented a basic version of this:
![image](https://user-images.githubusercontent.com/16945761/88710425-81a16d00-d0cb-11ea-91de-59aa16412cfc.png)
I think that it works pretty well, though it does create some weird situations such as this, where because the size of the wedge is not increased with the flexible position, there are solutions that don't seem possible (though mathematically they are totally correct)
![image](https://user-images.githubusercontent.com/16945761/88710376-6b93ac80-d0cb-11ea-863e-4c5b122e773a.png)

An interesting option would be to make everything the same color, and increase the size of the wedge to adjust for the flexible position. These are two versions with and without the original dot and line ee.
![image](https://user-images.githubusercontent.com/16945761/88711442-0a6cd880-d0cd-11ea-9361-a8ccf2880a10.png)
![image](https://user-images.githubusercontent.com/16945761/88711803-954dd300-d0cd-11ea-9ad4-0f2c49840959.png)

Even with the above solution, there are still oddities like this:
![image](https://user-images.githubusercontent.com/16945761/88712088-055c5900-d0ce-11ea-9190-66d914a558f1.png)
